project_name: nomad-gitops-operator
builds:
  -
    main: ./cmd/nomad-gitops-operator
    id: nomad-gitops-operator
    binary: nomad-gitops-operator
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  -
    format: binary

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "loq9/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "loq9/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "loq9/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "loq9/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: loq9/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - loq9/{{ .ProjectName }}:{{ .Version }}-amd64
      - loq9/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: loq9/{{ .ProjectName }}:latest
    image_templates:
      - loq9/{{ .ProjectName }}:latest-amd64
      - loq9/{{ .ProjectName }}:latest-arm64v8